// ══════════════════════════════════════════════════════════════════════════════
// src/lib/credits.ts — Credit ledger & atomic consumption helpers (Mission 6.0 P2.2)
// ══════════════════════════════════════════════════════════════════════════════
//
// This module is the SINGLE source of truth for credit balance mutations on
// the platform. Every credit movement (purchase, consumption, refund, reserve,
// release) goes through one of the exported helpers below.
//
// Data model (Prisma — see schema.prisma P2.1):
//   - Credit              : current balance + reserved per (weddingId, type)
//                           OR per (organizationId, type) when organizationId is set.
//   - CreditTransaction   : immutable append-only ledger (delta, reason, ...).
//   - CreditBalance       : materialized snapshot (lifetimePurchased/Consumed/Refunded).
//
// Atomicity:
//   All mutations run inside `db.$transaction(async (tx) => ...)`. SQLite
//   serializes writes (single writer), so re-reading the row inside the tx
//   gives us FOR-UPDATE-equivalent semantics: no other writer can change the
//   balance between the read and the write.
//
// Org-level fallback (white-label resellers):
//   When a wedding has `organizationId`, consumption first tries the wedding's
//   own Credit row. If insufficient, the org-level Credit row (matched by
//   `organizationId_type`) is drawn from. The CreditTransaction is always
//   written with the CURRENT wedding's id (for audit) + the org id (for org
//   billing aggregation). This mirrors the B2B2C contract: orgs pre-purchase
//   credits that are then drawn down by their individual weddings.
//
// Error contract:
//   `InsufficientCreditsError` is thrown when balance < required after both
//   wedding + org fallbacks are exhausted. Callers MUST catch it and return
//   HTTP 402 to the client (see bulk invitation route for an example).
//
// Logging:
//   Every successful consumption/purchase is logged at info level via the
//   structured logger — this gives observability into credit flow without
//   needing to scan the CreditTransaction ledger.
//
// ─── Imports ──────────────────────────────────────────────────────────────────
import { db } from './db';
import { logger } from './logger';
import { CREDIT_TYPES, type CreditType } from './constants';

// ─── Errors ───────────────────────────────────────────────────────────────────

/**
 * Thrown by `consumeCredit` when the wedding's balance (after org-level
 * fallback) is strictly less than `quantity`.
 *
 * Callers should catch this and return HTTP 402 Payment Required to the
 * client with a clear "buy more credits" message.
 */
export class InsufficientCreditsError extends Error {
  constructor(
    public readonly creditType: CreditType,
    public readonly required: number,
    public readonly available: number,
    public readonly weddingId: string
  ) {
    super(
      `Crédits insuffisants: ${creditType} besoin=${required}, disponible=${available}`
    );
    this.name = 'InsufficientCreditsError';
    // Restore prototype chain (TS quirk when extending built-in Error)
    Object.setPrototypeOf(this, InsufficientCreditsError.prototype);
  }
}

// ─── Internal helpers ─────────────────────────────────────────────────────────

/**
 * Prisma's compound-unique `where` keys. We use the snake_case form
 * `weddingId_type` and `organizationId_type` (auto-generated by Prisma from
 * the @@unique declarations in schema.prisma).
 */
function weddingTypeWhere(weddingId: string, type: CreditType) {
  return { weddingId_type: { weddingId, type } };
}

function orgTypeWhere(organizationId: string, type: CreditType) {
  return { organizationId_type: { organizationId, type } };
}

/**
 * Internal: fetch the wedding's organizationId (needed for org-fallback).
 * Returns null if the wedding has no org or doesn't exist.
 */
async function fetchWeddingOrgId(weddingId: string): Promise<string | null> {
  const w = await db.wedding.findUnique({
    where: { id: weddingId },
    select: { organizationId: true },
  });
  return w?.organizationId ?? null;
}

// ─── Public API ───────────────────────────────────────────────────────────────

/**
 * Get or create the Credit row for a wedding+type (idempotent upsert).
 *
 * Use this to ensure a row exists before incrementing/decrementing in a
 * custom transaction. For normal flows, prefer `consumeCredit` / `addCredits`
 * which call this internally.
 *
 * Returns the row's id + balance + reserved (after upsert).
 */
export async function ensureCreditRow(
  weddingId: string,
  type: CreditType
): Promise<{ id: string; balance: number; reserved: number }> {
  const row = await db.credit.upsert({
    where: weddingTypeWhere(weddingId, type),
    create: { weddingId, type, balance: 0, reserved: 0 },
    update: {},
    select: { id: true, balance: true, reserved: true },
  });
  return row;
}

/**
 * Check if a wedding has enough credits WITHOUT consuming them.
 *
 * Considers org-level fallback: if the wedding's own balance is insufficient
 * but the wedding belongs to an org with org-level credits, the ORG balance
 * is added to the available total.
 *
 * @returns { sufficient, available, required }
 */
export async function hasSufficientCredits(
  weddingId: string,
  type: CreditType,
  quantity: number
): Promise<{ sufficient: boolean; available: number; required: number }> {
  // Read wedding's own Credit row (org-unscoped — organizationId IS NULL).
  const weddingCredit = await db.credit.findUnique({
    where: weddingTypeWhere(weddingId, type),
    select: { balance: true },
  });
  let available = weddingCredit?.balance ?? 0;

  if (available < quantity) {
    // Try org-level fallback.
    const orgId = await fetchWeddingOrgId(weddingId);
    if (orgId) {
      const orgCredit = await db.credit.findUnique({
        where: orgTypeWhere(orgId, type),
        select: { balance: true },
      });
      if (orgCredit) {
        // Org-level credits are SHARED across the org's weddings. We add the
        // entire org balance to the wedding's own balance for the availability
        // check (the actual consumption will only draw what's needed).
        available += orgCredit.balance;
      }
    }
  }

  return {
    sufficient: available >= quantity,
    available,
    required: quantity,
  };
}

/**
 * Atomic credit consumption.
 *
 * Decrements the wedding's Credit.balance for the given type by `quantity`.
 * If the wedding's own balance is insufficient, falls back to the org-level
 * Credit row (when the wedding has an organizationId).
 *
 * Inside a single `db.$transaction`:
 *   1. Re-read the Credit row (FOR-UPDATE-equivalent on SQLite).
 *   2. If balance < quantity, try org-level fallback.
 *   3. If still insufficient, throw InsufficientCreditsError (caller returns 402).
 *   4. UPDATE the Credit row's balance (-= quantity).
 *   5. INSERT a CreditTransaction (delta = -quantity, reason = 'CONSUMPTION').
 *   6. UPSERT the CreditBalance aggregate (lifetimeConsumed += quantity, currentBalance -= quantity).
 *
 * @throws {InsufficientCreditsError} if neither wedding nor org has enough.
 */
export async function consumeCredit(params: {
  weddingId: string;
  type: CreditType;
  quantity: number;
  sourceDeliveryJobId?: string;
  note?: string;
  createdBy?: string;
}): Promise<{ newBalance: number; consumed: number }> {
  const { weddingId, type, quantity, sourceDeliveryJobId, note, createdBy } =
    params;

  if (quantity <= 0) {
    throw new Error(`consumeCredit: quantity must be > 0 (got ${quantity})`);
  }

  return db.$transaction(async (tx) => {
    // 1. Re-read wedding's own Credit row inside the tx.
    const weddingCredit = await tx.credit.findUnique({
      where: weddingTypeWhere(weddingId, type),
      select: { id: true, balance: true, organizationId: true },
    });

    let consumeFromCreditId: string;
    let consumeOrgId: string | null = null;
    let newBalance: number;
    let oldBalance: number;

    if (weddingCredit && weddingCredit.balance >= quantity) {
      // Path A: consume from wedding's own balance.
      consumeFromCreditId = weddingCredit.id;
      oldBalance = weddingCredit.balance;
      newBalance = oldBalance - quantity;
      await tx.credit.update({
        where: { id: consumeFromCreditId },
        data: { balance: newBalance },
      });
    } else {
      // Path B: try org-level fallback.
      const orgId = weddingCredit?.organizationId ?? (await fetchWeddingOrgId(weddingId));
      if (!orgId) {
        const available = weddingCredit?.balance ?? 0;
        throw new InsufficientCreditsError(type, quantity, available, weddingId);
      }
      const orgCredit = await tx.credit.findUnique({
        where: orgTypeWhere(orgId, type),
        select: { id: true, balance: true },
      });
      const weddingBalance = weddingCredit?.balance ?? 0;
      const orgBalance = orgCredit?.balance ?? 0;
      if (weddingBalance + orgBalance < quantity) {
        throw new InsufficientCreditsError(
          type,
          quantity,
          weddingBalance + orgBalance,
          weddingId
        );
      }

      // Consume from org-level balance.
      if (!orgCredit) {
        throw new InsufficientCreditsError(type, quantity, weddingBalance, weddingId);
      }
      consumeFromCreditId = orgCredit.id;
      consumeOrgId = orgId;
      oldBalance = orgCredit.balance;
      newBalance = oldBalance - quantity;
      await tx.credit.update({
        where: { id: consumeFromCreditId },
        data: { balance: newBalance },
      });
    }

    // 5. Append the ledger entry. delta is NEGATIVE for consumption.
    await tx.creditTransaction.create({
      data: {
        weddingId,
        organizationId: consumeOrgId,
        creditType: type,
        creditId: consumeFromCreditId,
        delta: -quantity,
        reason: 'CONSUMPTION',
        sourceDeliveryJobId: sourceDeliveryJobId ?? null,
        note: note ?? null,
        createdBy: createdBy ?? null,
      },
    });

    // 6. Update the wedding's CreditBalance aggregate (regardless of which
    //    Credit row was drawn from — the aggregate is per-wedding).
    await tx.creditBalance.upsert({
      where: weddingTypeWhere(weddingId, type),
      create: {
        weddingId,
        type,
        lifetimePurchased: 0,
        lifetimeConsumed: quantity,
        lifetimeRefunded: 0,
        currentBalance: newBalance,
      },
      update: {
        lifetimeConsumed: { increment: quantity },
        currentBalance: { decrement: quantity },
      },
    });

    logger.info('consumeCredit', {
      weddingId,
      type,
      quantity,
      newBalance,
      orgLevel: consumeOrgId !== null,
      organizationId: consumeOrgId ?? undefined,
      createdBy: createdBy ?? undefined,
    });

    return { newBalance, consumed: quantity };
  });
}

/**
 * Add credits to a wedding (purchase, refund, or manual adjustment).
 *
 * Inside a single `db.$transaction`:
 *   1. Upsert the Credit row, incrementing balance by `quantity`.
 *   2. Insert a CreditTransaction (delta = +quantity, reason = 'PURCHASE' | 'REFUND' | 'ADJUSTMENT').
 *   3. Upsert the CreditBalance aggregate:
 *        - PURCHASE  → lifetimePurchased += quantity
 *        - REFUND    → lifetimeRefunded += quantity
 *        - ADJUSTMENT→ no lifetime change (admin-only adjustment)
 *      currentBalance += quantity in all cases.
 *
 * @returns { newBalance } the post-add balance for this (wedding, type) pair.
 */
export async function addCredits(params: {
  weddingId: string;
  type: CreditType;
  quantity: number;
  sourceOrderId?: string;
  reason?: 'PURCHASE' | 'REFUND' | 'ADJUSTMENT';
  note?: string;
  createdBy?: string;
}): Promise<{ newBalance: number }> {
  const {
    weddingId,
    type,
    quantity,
    sourceOrderId,
    reason = 'PURCHASE',
    note,
    createdBy,
  } = params;

  if (quantity <= 0) {
    throw new Error(`addCredits: quantity must be > 0 (got ${quantity})`);
  }

  return db.$transaction(async (tx) => {
    // 1. Upsert + increment balance.
    const updated = await tx.credit.upsert({
      where: weddingTypeWhere(weddingId, type),
      create: { weddingId, type, balance: quantity, reserved: 0 },
      update: { balance: { increment: quantity } },
      select: { id: true, balance: true },
    });

    // 2. Append ledger entry (delta positive).
    await tx.creditTransaction.create({
      data: {
        weddingId,
        creditType: type,
        creditId: updated.id,
        delta: quantity,
        reason,
        sourceOrderId: sourceOrderId ?? null,
        note: note ?? null,
        createdBy: createdBy ?? null,
      },
    });

    // 3. Update aggregate snapshot.
    const balanceUpdate: { lifetimePurchased?: { increment: number }; lifetimeRefunded?: { increment: number }; currentBalance: { increment: number } } = {
      currentBalance: { increment: quantity },
    };
    if (reason === 'PURCHASE') {
      balanceUpdate.lifetimePurchased = { increment: quantity };
    } else if (reason === 'REFUND') {
      balanceUpdate.lifetimeRefunded = { increment: quantity };
    }
    // ADJUSTMENT: no lifetime counter change (admin-only balance correction).

    await tx.creditBalance.upsert({
      where: weddingTypeWhere(weddingId, type),
      create: {
        weddingId,
        type,
        lifetimePurchased: reason === 'PURCHASE' ? quantity : 0,
        lifetimeConsumed: 0,
        lifetimeRefunded: reason === 'REFUND' ? quantity : 0,
        currentBalance: quantity,
      },
      update: balanceUpdate,
    });

    logger.info('addCredits', {
      weddingId,
      type,
      quantity,
      reason,
      newBalance: updated.balance,
      sourceOrderId: sourceOrderId ?? undefined,
      createdBy: createdBy ?? undefined,
    });

    return { newBalance: updated.balance };
  });
}

/**
 * Read a single credit type's balance for a wedding.
 *
 * Returns zeros for all fields if no Credit/CreditBalance rows exist yet
 * (new wedding, no purchases made yet).
 */
export async function getCreditBalance(
  weddingId: string,
  type: CreditType
): Promise<{
  balance: number;
  reserved: number;
  available: number;
  lifetimePurchased: number;
  lifetimeConsumed: number;
}> {
  const [credit, aggregate] = await Promise.all([
    db.credit.findUnique({
      where: weddingTypeWhere(weddingId, type),
      select: { balance: true, reserved: true },
    }),
    db.creditBalance.findUnique({
      where: weddingTypeWhere(weddingId, type),
      select: { lifetimePurchased: true, lifetimeConsumed: true, lifetimeRefunded: true },
    }),
  ]);

  const balance = credit?.balance ?? 0;
  const reserved = credit?.reserved ?? 0;
  return {
    balance,
    reserved,
    available: Math.max(0, balance - reserved),
    lifetimePurchased: aggregate?.lifetimePurchased ?? 0,
    lifetimeConsumed: aggregate?.lifetimeConsumed ?? 0,
  };
}

/**
 * Read ALL credit types for a wedding in one call.
 *
 * Returns a record keyed by CreditType. Each entry has balance/reserved/
 * available (lifetime totals are omitted here — use getCreditBalance for
 * those). Missing rows return zeros.
 */
export async function getAllCredits(
  weddingId: string
): Promise<
  Record<CreditType, { balance: number; reserved: number; available: number }>
> {
  const rows = await db.credit.findMany({
    where: { weddingId },
    select: { type: true, balance: true, reserved: true },
  });
  const byType = new Map(rows.map((r) => [r.type as CreditType, r]));

  const out = {} as Record<CreditType, { balance: number; reserved: number; available: number }>;
  for (const t of CREDIT_TYPES) {
    const r = byType.get(t);
    const balance = r?.balance ?? 0;
    const reserved = r?.reserved ?? 0;
    out[t] = { balance, reserved, available: Math.max(0, balance - reserved) };
  }
  return out;
}

/**
 * Reserve credits (move from `balance` to `reserved`) for an in-flight
 * operation that hasn't yet been consumed (e.g. queued SMS awaiting provider
 * ack). Reserved credits are NOT available for new consumption but ARE still
 * "owned" by the wedding — they will either be:
 *   - consumed later (consumeCredit will draw from `balance` first, then
 *     fall back to `reserved` if needed in a future revision), OR
 *   - released back to `balance` via `releaseReservedCredits` (operation
 *     cancelled/failed before consumption).
 *
 * @throws {InsufficientCreditsError} if available balance < quantity.
 */
export async function reserveCredits(params: {
  weddingId: string;
  type: CreditType;
  quantity: number;
}): Promise<{ success: boolean; reserved: number }> {
  const { weddingId, type, quantity } = params;
  if (quantity <= 0) {
    throw new Error(`reserveCredits: quantity must be > 0 (got ${quantity})`);
  }

  try {
    const result = await db.$transaction(async (tx) => {
      const credit = await tx.credit.findUnique({
        where: weddingTypeWhere(weddingId, type),
        select: { id: true, balance: true, reserved: true },
      });
      const balance = credit?.balance ?? 0;
      const available = Math.max(0, balance - (credit?.reserved ?? 0));
      if (available < quantity) {
        throw new InsufficientCreditsError(type, quantity, available, weddingId);
      }
      if (!credit) {
        // Should be unreachable given available < quantity check above.
        throw new InsufficientCreditsError(type, quantity, 0, weddingId);
      }
      const newReserved = (credit.reserved ?? 0) + quantity;
      await tx.credit.update({
        where: { id: credit.id },
        data: { balance: { decrement: quantity }, reserved: newReserved },
      });
      return { success: true as const, reserved: newReserved };
    });
    logger.info('reserveCredits', { weddingId, type, quantity, reserved: result.reserved });
    return result;
  } catch (e) {
    if (e instanceof InsufficientCreditsError) throw e;
    throw e;
  }
}

/**
 * Release previously-reserved credits back to the available balance
 * (operation cancelled/failed before consumption).
 *
 * Idempotent: if `quantity` exceeds the current reserved count, only the
 * actual reserved amount is released (no negative reserved).
 */
export async function releaseReservedCredits(params: {
  weddingId: string;
  type: CreditType;
  quantity: number;
}): Promise<void> {
  const { weddingId, type, quantity } = params;
  if (quantity <= 0) {
    throw new Error(`releaseReservedCredits: quantity must be > 0 (got ${quantity})`);
  }

  await db.$transaction(async (tx) => {
    const credit = await tx.credit.findUnique({
      where: weddingTypeWhere(weddingId, type),
      select: { id: true, balance: true, reserved: true },
    });
    if (!credit) return; // nothing to release
    const releaseQty = Math.min(quantity, credit.reserved);
    if (releaseQty <= 0) return;
    await tx.credit.update({
      where: { id: credit.id },
      data: {
        balance: { increment: releaseQty },
        reserved: { decrement: releaseQty },
      },
    });
  });

  logger.info('releaseReservedCredits', { weddingId, type, quantity });
}
