/**
 * Mission 5.9.5-B Phase 2.5/2.6 — CHAROW SANDBOX SALE INFO (public read)
 * GET /api/charow/sandbox-sale?sale=<saleId>
 *
 * Returns the sandbox sale record (amount, currency, description, status)
 * so the /charow/pay page can display the order summary to the customer
 * BEFORE they click "Payer maintenant".
 *
 * SECURITY:
 *   - Returns 403 in PRODUCTION mode (the /charow/pay page itself is hidden
 *     in production — this endpoint is defence-in-depth).
 *   - Returns 404 if the saleId is not in the in-memory sandboxLedger
 *     (server was restarted, or the saleId is fake).
 *   - Returns 200 with { saleId, reference, amount, currency, description,
 *     status, paidAt, createdAt } if found.
 *   - No auth required: the saleId is a random unguessable token
 *     (`chr_<base36>`) generated by charowProvider.createCheckoutSandbox.
 *     Possession of the saleId (via the checkout URL) is the only auth.
 *
 * NOTE: This endpoint reads from the in-memory `sandboxLedger` exported by
 * `src/lib/payment/charow.ts`. It REUSES existing code — no new commercial
 * engine is created. The ledger is cleared on server restart (intentional
 * sandbox behaviour — already documented in payment-charow.ts).
 */
import { NextResponse } from 'next/server'
import { charowProvider, sandboxLedger } from '@/lib/payment/charow'

export const dynamic = 'force-dynamic'

export async function GET(req: Request) {
  // Defence-in-depth: never expose sandbox sale data in production mode.
  if (charowProvider.mode !== 'SANDBOX') {
    return NextResponse.json(
      { error: 'Route disponible uniquement en mode SANDBOX.' },
      { status: 403 }
    )
  }

  const url = new URL(req.url)
  const saleId = url.searchParams.get('sale') ?? ''
  if (!saleId) {
    return NextResponse.json(
      { error: 'Paramètre "sale" requis.' },
      { status: 400 }
    )
  }

  const sale = sandboxLedger.get(saleId)
  if (!sale) {
    return NextResponse.json(
      { error: 'Sale introuvable (sandbox redémarré ou saleId invalide).' },
      { status: 404 }
    )
  }

  // Return the public-facing fields only. Do NOT expose customerEmail or
  // customerName (PII) — the customer already knows who they are.
  return NextResponse.json({
    saleId: sale.saleId,
    reference: sale.reference,
    amount: sale.amount, // in cents (matches Payment.amount)
    currency: sale.currency,
    description: sale.description,
    status: sale.status, // PENDING | PAID | CANCELLED | FAILED
    paidAt: sale.paidAt,
    createdAt: sale.createdAt,
  })
}
